In [ ]:
# 1 ?
import numpy as np
a=np.arange(0,10)
print(a)

[0 1 2 3 4 5 6 7 8 9]


In [1]:
# 2?
import numpy as np
a=np.arange(1,10).reshape((3,3))

print(a)

[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [ ]:
#3?
import numpy as np
a=np.eye(3,3)
print(a)

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


In [6]:
# 4?
import numpy as np
a=np.random.rand(10).round(2)
print(a)

[0.75 0.45 0.02 0.65 0.71 0.7  0.82 0.52 0.62 0.03]


In [ ]:
#5?
import numpy as np
a=np.zeros(10)
b=np.ones(10)
print(a)
print(b)

[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
[1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]


In [ ]:
#6?
import numpy as np
a=np.array([10,20,30,40,50])
print(a[2])

30


In [ ]:
#7?
import numpy as np
a=np.arange(1,17)
b=a.reshape(4,4)
print(b)
print(b[1,2])

[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]
 [13 14 15 16]]
7


In [ ]:
#8?
import numpy as np
a=np.array([5,10,16,20,25])
print(a[-1])

25


In [9]:
#9?
import numpy as np
a=np.array([1,3,5,7,9,11])
b=a[[1,3,4]]
print(b)

[3 7 9]


In [ ]:
#10?
import numpy as np
a=np.arange(1,9)
b=a.reshape((2,2,2))
print(b,"\n")
print(b[1,1,1])


[[[1 2]
  [3 4]]

 [[5 6]
  [7 8]]] 

8


In [ ]:
#11?
import numpy as np
a=np.array([2,4,6,8,10,12])
print(a[:3])

[2 4 6]


In [10]:
#12?
import numpy as np
a=np.arange(1,17)
b=a.reshape((4,4))
print(b,"\n")
print(b[:2,-2:])

[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]
 [13 14 15 16]] 

[[3 4]
 [7 8]]


In [ ]:
# 13?
import numpy as np
a=np.array([0,1,2,3,4,5,6,7,8,9])
print(a[::2])

[0 2 4 6 8]


In [11]:
# 14?
import numpy as np
a=np.arange(1,13)
b=a.reshape((3,4))
print(b,"\n")
print(b[:,2:])

[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]] 

[[ 3  4]
 [ 7  8]
 [11 12]]


In [ ]:
# 15?
import numpy as np
a=np.arange(1,26)
b=a.reshape((5,5))
print(b,"\n")
print(b[1:-1,1:4])

[[ 1  2  3  4  5]
 [ 6  7  8  9 10]
 [11 12 13 14 15]
 [16 17 18 19 20]
 [21 22 23 24 25]] 

[[ 7  8  9]
 [12 13 14]
 [17 18 19]]


In [12]:
# 16?
a=np.arange(0,6)
b=a.astype("f")
print(b)

[0. 1. 2. 3. 4. 5.]


"F

In [34]:
#17?
import numpy as np
a=np.array([[0,1,3],[1,2,0]])
b=a.astype("b")
print(b,"\n")

c=np.array([[True,False,True],
           [False,True,False]])
d=c.astype("b")
print(d)

[[0 1 3]
 [1 2 0]] 

[[1 0 1]
 [0 1 0]]


In [30]:
#18?
import numpy as np
a=np.array([1+2j,3+4j,5+6j])
b=a.astype("F")# we can give capital F for complex float in new versions like colab
print(b)

[1.+2.j 3.+4.j 5.+6.j]


In [ ]:
#19?
import numpy as np
a=np.array(["1","2","3"])
b=a.astype(int)
print(b)

[1 2 3]


In [ ]:
# 20?
a=np.array([1.5,1.2,2.5,3.5])
b=a.astype(int)
print(b)

[1 1 2 3]
