In [ ]:
# 1?
import numpy as np

a=np.arange(1,4)
b=np.arange(4,7)
c=np.concatenate((a,b))
print(c)

[1 2 3 4 5 6]


In [ ]:
# 2?
import numpy as np
a=np.arange(1,4)
b=np.arange(4,7)
c=np.stack((a,b),axis=1)
print(c)

[[1 4]
 [2 5]
 [3 6]]


In [ ]:
# 3?
import numpy as np
a=np.arange(1,4)
b=np.arange(4,7)
c=np.stack((a,b))
print(c)

[[1 2 3]
 [4 5 6]]


In [ ]:
# 4?
import numpy as np
a=np.arange(1,4)
b=np.arange(4,7)
c=np.arange(7,10)
d=np.stack((a,b,c))
print(d)

[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [ ]:
# 5?
import numpy as np
a=np.array([[1,2,],[3,4]])
b=np.array([[5,6],[7,8]])
c=np.stack((a,b),axis=1)
print(c)

[[[1 2]
  [5 6]]

 [[3 4]
  [7 8]]]


In [ ]:
# 6?
import numpy as np
a=np.arange(1,7)
b=np.array_split(a,3)
print(b)

[array([1, 2]), array([3, 4]), array([5, 6])]


In [ ]:
# 7?
import numpy as np
a=np.array([[1,2],[3,4],[5,6]])
b=np.array_split(a,2)
print(b)

[array([[1, 2],
       [3, 4]]), array([[5, 6]])]


In [ ]:
# 8?
import numpy as np
a=np.arange(1,8)
b=np.array_split(a,3)
print(b)

[array([1, 2, 3]), array([4, 5]), array([6, 7])]


In [ ]:
# 9?
import numpy as np
a=np.array([[1,2,3],[4,5,6],[7,8,9],[10,11,12]])
b=np.array_split(a,3,axis=1)
print(b)

[array([[ 1],
       [ 4],
       [ 7],
       [10]]), array([[ 2],
       [ 5],
       [ 8],
       [11]]), array([[ 3],
       [ 6],
       [ 9],
       [12]])]


In [ ]:
# 10?
import numpy as np
a=np.arange(1,10)
b=np.array_split(a,3)
print(b)

[array([1, 2, 3]), array([4, 5, 6]), array([7, 8, 9])]


In [ ]:
# 11?
import numpy as np
a=np.arange(1,7)
b=np.searchsorted(a,4)
print(b)

3


In [ ]:
# 12?
import numpy as np
a=np.array([10,20,30,40,50])
b=np.max(a)
print(b)

50


In [ ]:
# 13?
import numpy as np
a=np.array([5,10,15,20,25])
b=np.where(a>10)
print(b)

(array([2, 3, 4]),)


In [ ]:
# 14?
import numpy as np
a=np.array([[1,2,3],[4,5,6],[7,8,9]])
b=np.where(a==7)
print(b)


(array([2]), array([0]))


In [ ]:
# 15?
import numpy as np
a=np.array([10,20,30,40,50])
b=np.where(a>=30)
print(b)

(array([2, 3, 4]),)


In [ ]:
# 16?
import numpy as np
a=np.array([9,2,5,1,7])
print(np.sort(a))

[1 2 5 7 9]


In [ ]:
# 17?
import numpy as np
a=np.array([[1,4,3],[6,5,2]])
print(np.sort(a[:,1:2]))

[[4]
 [5]]


In [ ]:
# 18?
import numpy as np
a=np.array([[3,2,1],[6,5,4]])
b=np.sort((a))
print(b)

[[1 2 3]
 [4 5 6]]


In [ ]:
# 19?
import numpy as np
a=np.array([30,10,50,40,20])
b=np.argsort(a)
print(b)

[1 4 0 3 2]


In [ ]:
# 20?
import numpy as np
a=np.array(["banana","cherry","apple"])
print(np.sort(a))

['apple' 'banana' 'cherry']


In [ ]:
# 21?
import numpy as np
a=np.array([1,2,3,4,5,6])
print(a[a>3])

[4 5 6]


In [ ]:
# 22?
import numpy as np
a=np.array([10,15,20,25,30])
b=np.logical_and(a>15,a<30)
print(a[b])

[20 25]


In [ ]:
# 23?
import numpy as np
a=np.array([[1,2],[3,4],[5,6]])
print(a[a>2])

[3 4 5 6]


In [42]:
# 24?
import numpy as np
a=np.array([1,2,3,4,5,6])
b=a%2==0
print(b)

[False  True False  True False  True]


In [48]:
# 25?
import numpy as np
a=np.array([10,25,30,15,50])
m1=np.where(a>20)
a[m1]=0
print(a)

[10  0  0 15  0]
