In [1]:

import numpy as np

In [5]:
# 1?
x=np.array([[6,7,4,7,8],[4,5,3,2,1],[5,6,8,9,0]])
a=x[1,1:4]
print(a,"\n")
b=x[:,:4]
print(b,"\n")
c=x.transpose()
print(c)

[5 3 2] 

[[6 7 4 7]
 [4 5 3 2]
 [5 6 8 9]] 

[[6 4 5]
 [7 5 6]
 [4 3 8]
 [7 2 9]
 [8 1 0]]


In [7]:
# 2?
import random
a=np.random.randint(20,45,3)
print(a)


[29 38 36]


In [12]:
# 3?
a=np.ones(64).reshape((8,8))
print(a,"\n")
a[::2,::2]=0
a[1::2,1::2]=0
print(a)


[[1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1.]] 

[[0. 1. 0. 1. 0. 1. 0. 1.]
 [1. 0. 1. 0. 1. 0. 1. 0.]
 [0. 1. 0. 1. 0. 1. 0. 1.]
 [1. 0. 1. 0. 1. 0. 1. 0.]
 [0. 1. 0. 1. 0. 1. 0. 1.]
 [1. 0. 1. 0. 1. 0. 1. 0.]
 [0. 1. 0. 1. 0. 1. 0. 1.]
 [1. 0. 1. 0. 1. 0. 1. 0.]]


In [21]:
# 4?
a=[1,2,3,4,5,6,7,8]
b=np.array(a)
print(b,"\n")
c=([8,4,6],[1,2,3])
d=np.array(c)
print(d)

[1 2 3 4 5 6 7 8] 

[[8 4 6]
 [1 2 3]]


In [29]:
# 5?
a=np.arange(1,13).reshape((-1,2,3))
print(a,"\n")
a[1,0,1]=0
print(a)

[[[ 1  2  3]
  [ 4  5  6]]

 [[ 7  8  9]
  [10 11 12]]] 

[[[ 1  2  3]
  [ 4  5  6]]

 [[ 7  0  9]
  [10 11 12]]]


In [34]:
# 6?
a=np.array([1.1,1.2,1.3])
b=a.astype(int)
print(b)

[1 1 1]


In [49]:
# 7?
a=np.zeros(49).reshape((7,7))
print(a,"\n")
a[1,1:-1]=1
a[1:-1,1::4]=1
a[2,2:5]=2
a[3,2:5]=2
a[3,3]=3
a[4,2:5]=2
a[5,1:-1]=1
print(a)

[[0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0.]] 

[[0. 0. 0. 0. 0. 0. 0.]
 [0. 1. 1. 1. 1. 1. 0.]
 [0. 1. 2. 2. 2. 1. 0.]
 [0. 1. 2. 3. 2. 1. 0.]
 [0. 1. 2. 2. 2. 1. 0.]
 [0. 1. 1. 1. 1. 1. 0.]
 [0. 0. 0. 0. 0. 0. 0.]]


In [51]:
# 8?
a=np.array([[1,2],[4,6],[8,9],[2,2]])
b=a.transpose()
print(b)

[[1 4 8 2]
 [2 6 9 2]]


In [56]:
# 9?
c=np.array([[[5,6,7],[7,8,9]],[[0,4,8],[2,3,1]],[[9,5,3],[0,4,5]]])
a=c[:,1,1]
print(a,"\n")

d=np.array([[[11,10,12],[88,0,45]],[[90,78,33],[41,77,0]],[[8,9,90],[12,67,9]]])
b=d[:,0,::2]
print(b)

[8 3 4] 

[[11 12]
 [90 33]
 [ 8 90]]


In [68]:
# 10?
a=np.zeros(42).reshape(6,7)
print(a,"\n")
a[:4:3,1::2]=1
a[2::3,0::2]=1
print(a)



[[0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0.]] 

[[0. 1. 0. 1. 0. 1. 0.]
 [0. 0. 0. 0. 0. 0. 0.]
 [1. 0. 1. 0. 1. 0. 1.]
 [0. 1. 0. 1. 0. 1. 0.]
 [0. 0. 0. 0. 0. 0. 0.]
 [1. 0. 1. 0. 1. 0. 1.]]
